export const linkedinJobTemplates = [
  "🚀 Exciting Job Opportunity! \n\nLooking to take your career to the next level? \n{companyName} is hiring for {jobRole}—a fantastic chance to join a team driving real impact. \n\n💡 Check out the job details in the below url and apply today! \n\n👉 Apply here: {jobURL} \n\n👉 Join us for updates on Twitter: {twitterLink} \n👉 Connect on Telegram: {telegramLink} \n👉 Follow here for more opportunities! \n\n#CareerGrowth #JobSearch #HiringNow #JoinTheTeam",

  "🌟 Attention Innovators! \n\nAn incredible opportunity awaits at {companyName}! \n{companyName} is looking for a {jobRole} to help shape the future. \n\nCheck the job details and make your move today! \n\n➡️ Job URL: {jobURL} \n\n➡️ Stay updated on Twitter: {twitterLink} \n➡️ Chat with us on Telegram: {telegramLink} \n➡️ Follow here for more updates! \n\n#JobAlert #InnovatorsWanted #CareerOpportunities",

  "✨ Make an Impact with Your Career! \n\nWe’re thrilled to share this exciting opportunity at {companyName}! The team is hiring a {jobRole}—an incredible chance to work with {companyName}. \n\nDon’t miss out—apply today! \n\n🌐 Apply link: {jobURL} \n\n🌐 Follow us on Twitter: {twitterLink} \n🌐 Join us on Telegram: {telegramLink} \n🌐 Follow for more opportunities! \n\n#DreamJob #ImpactfulCareers #WeAreHiring",

  "🚀 Ready to Grow Your Career? \n\nWe’ve got an amazing opportunity for a {jobRole} at {companyName}! This is your chance to work with a team that values innovation, creativity, collaboration etc. \n\n👉 Apply now: {jobURL}\n\n👉 Follow on Twitter for updates: {twitterLink} \n👉 Join the conversation on Telegram: {telegramLink} \n👉 Follow for more roles here! \n\n#CareerGrowth #JobsNow #WorkWithUs",

  "🔍 Spotlight on Opportunity! \n\nLooking for a new challenge? {companyName} is hiring a {jobRole}, and it might just be your perfect fit! \n\nDetails are in the image—don’t wait to apply! \n\n🔗 Apply now: {jobURL} \n\n🔗 Follow us on Twitter for news: {twitterLink} \n🔗 Join us on Telegram: {telegramLink} \n🔗 Stay tuned here for updates! \n\n#HiringAlert #NewCareer #JobSearch",

  "💼 Collaborate with the Best! \n\nWe’re excited to share this job opportunity at {companyName} for a {jobRole}! Be part of a incredible team. \n\n📜 See details in the image and apply today. \n\n🚀 Job url: {jobURL} \n\n🚀 Stay updated via Twitter: {twitterLink} \n🚀 Join us on Telegram: {telegramLink} \n🚀 Follow here for more updates! \n\n#JobPosting #HiringNow #Teamwork",

  "🌟 Help Build the Future! \n\nWe’re looking for a talented {jobRole} to join {companyName}! Don’t miss the chance to work with cutting-edge technology and a forward-thinking team. \n\n📌 Check out the job description in the image and apply today! \n\n👉 Take the advantage of applying early: {jobURL} \n\n👉 Follow us on Twitter: {twitterLink} \n👉 Join the discussion on Telegram: {telegramLink} \n👉 Follow here for more updates and roles! \n\n#FutureCareers #DreamBig #NowHiring",

  "✨ Collaborate with the Best! \n\nJoin {companyName} as a {jobRole} and grow your career with an organization making waves. \n\n📜 Full details are in the image! \n\n➡️ Apply now: {jobURL}\n\n➡️ Stay in the loop on Twitter: {twitterLink} \n➡️ Connect on Telegram: {telegramLink} \n➡️ Follow here for more opportunities! \n\n#GrowingTeam #CareerOpportunities #WorkLife",

  "🔍 Calling Problem-Solvers! \n\nDo you thrive on challenges and innovation? {companyName} is looking for a {jobRole} to join our amazing team. \n\n📌 Details are in the image. Ready to take the leap? \n\n🌟 Apply today: {jobURL} \n\n🌟 Stay updated on Twitter: {twitterLink} \n🌟 Join the conversation on Telegram: {telegramLink} \n🌟 Follow here for more updates! \n\n#CareerGoals #JobOpenings #TechCareers",

  "🚨 Don’t Miss This Opportunity! \n\nA fantastic role for a {jobRole} is open at {companyName}. Whether you’re ready for a new challenge or know someone who’d be perfect. \n\n👉 Don’t wait for the deadline: {jobURL} \n\n👉 Follow for updates on Twitter: {twitterLink} \n👉 Join us on Telegram: {telegramLink} \n👉 Follow here for more amazing opportunities! \n\n#DreamJob #JobsNow #OpportunityKnocks",
];
